### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Spaceflyer234** [GrooveProgramming/editor#11]
What license should we use for all our repos?

**Comment by B294** [comment]
I don’t know anything about licensing.

**Comment by Spaceflyer234** [comment]
> I don’t know anything about licensing.

Me neither.

**Comment by B294** [comment]
> > I don’t know anything about licensing.
> 
> Me neither.
https://github.com/reruns/mario Fork this or copy the code so we can start our game. Then invite me

**Comment by Mapletron** [comment]
The GrooveEditor is currently placed under the Apache License 2.0.

**Comment by Spaceflyer234** [comment]
> The GrooveEditor is currently placed under the Apache License 2.0.

I think the MIT License looks best for us.

**Comment by B294** [comment]
> > The GrooveEditor is currently placed under the Apache License 2.0.
> 
> I think the MIT License looks best for us.

Because we forked Blockly.

**Comment by B294** [comment]
@Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/

**Comment by Mapletron** [comment]
> @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
Sign up isn’t exactly necessary, maybe we should scrap it.

**Comment by B294** [comment]
> > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> 
> Sign up isn’t exactly necessary, maybe we should scrap it.

Then we’re pretty much done with Groove. :P

**Comment by Mapletron** [comment]
> > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > 
> > 
> > Sign up isn’t exactly necessary, maybe we should scrap it.
> 
> Then we’re pretty much done with Groove. :P

well there’s, way more blocks, a stage, ability to import sounds, any bug fixes a proper stage and a better paint editor :P

**Comment by Spaceflyer234** [comment]
> > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > 
> > 
> > Sign up isn’t exactly necessary, maybe we should scrap it.
> 
> Then we’re pretty much done with Groove. :P

No, users could share projects by entering the projects name and clicking share.

**Comment by B294** [comment]
> > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > 
> > > 
> > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > 
> > 
> > Then we’re pretty much done with Groove. :P
> 
> Well we need way more blocks, a stage, ability to import sounds, any bug fixes a proper stage and a better paint editor :P

And all that just to advertise it on Scratch? We don’t necessarily have to ask for a email. I’ll talk to Jimmyrooster.  @JimmyRooster

**Comment by Mapletron** [comment]
Should we or should we not get rid of the sign ups? They don’t need to exist.

**Comment by B294** [comment]
> Should we or should we not get rid of the sign ups? They don’t need to exist.

I don’t know

**Comment by B294** [comment]
> > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > 
> > > 
> > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > 
> > 
> > Then we’re pretty much done with Groove. :P
> 
> No, users could share projects by entering the projects name and clicking share.

That’s a little complicated to moderate

**Comment by Mapletron** [comment]
> > > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > > 
> > > > 
> > > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > > 
> > > 
> > > Then we’re pretty much done with Groove. :P
> > 
> > 
> > No, users could share projects by entering the projects name and clicking share.
> 
> That’s a little complicated to moderate

IP bans

**Comment by B294** [comment]
> > > > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > > > 
> > > > > 
> > > > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > > > 
> > > > 
> > > > Then we’re pretty much done with Groove. :P
> > > 
> > > 
> > > No, users could share projects by entering the projects name and clicking share.
> > 
> > 
> > That’s a little complicated to moderate
> 
> IP bans

But still, Scratch won’t allow us even after that! Because of moderation issues, currently we have no worries of that. But it’ll come to that.

**Comment by Mapletron** [comment]
> > > > > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > > > > 
> > > > > > 
> > > > > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > > > > 
> > > > > 
> > > > > Then we’re pretty much done with Groove. :P
> > > > 
> > > > 
> > > > No, users could share projects by entering the projects name and clicking share.
> > > 
> > > 
> > > That’s a little complicated to moderate
> > 
> > 
> > IP bans
> 
> But still, Scratch won’t allow us even after that! Because of moderation issues, currently we have no worries of that. But it’ll come to that.

for now it’s okay for Scratch, if we want to continue this forward we’ll probably have to speak with an ST member

**Comment by B294** [comment]
> > > > > > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > > > > > 
> > > > > > > 
> > > > > > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > > > > > 
> > > > > > 
> > > > > > Then we’re pretty much done with Groove. :P
> > > > > 
> > > > > 
> > > > > No, users could share projects by entering the projects name and clicking share.
> > > > 
> > > > 
> > > > That’s a little complicated to moderate
> > > 
> > > 
> > > IP bans
> > 
> > 
> > But still, Scratch won’t allow us even after that! Because of moderation issues, currently we have no worries of that. But it’ll come to that.
> 
> for now it’s okay for Scratch, if we want to continue this forward we’ll probably have to speak with an ST member

Yep, or we have to think of a domain idea.

**Comment by Mapletron** [comment]
> > > > > > > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > > > > > > 
> > > > > > > 
> > > > > > > Then we’re pretty much done with Groove. :P
> > > > > > 
> > > > > > 
> > > > > > No, users could share projects by entering the projects name and clicking share.
> > > > > 
> > > > > 
> > > > > That’s a little complicated to moderate
> > > > 
> > > > 
> > > > IP bans
> > > 
> > > 
> > > But still, Scratch won’t allow us even after that! Because of moderation issues, currently we have no worries of that. But it’ll come to that.
> > 
> > 
> > for now it’s okay for Scratch, if we want to continue this forward we’ll probably have to speak with an ST member
> 
> Yep, or we have to think of a domain idea.

Wdym “domain idea”?

**Comment by B294** [comment]
> > > > > > > > > > @Spaceflyer234 We can’t ask for email, and it technically asks for personal info. Read this: https://scratch.mit.edu/discuss/topic/4421/
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Sign up isn’t exactly necessary, maybe we should scrap it.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Then we’re pretty much done with Groove. :P
> > > > > > > 
> > > > > > > 
> > > > > > > No, users could share projects by entering the projects name and clicking share.
> > > > > > 
> > > > > > 
> > > > > > That’s a little complicated to moderate
> > > > > 
> > > > > 
> > > > > IP bans
> > > > 
> > > > 
> > > > But still, Scratch won’t allow us even after that! Because of moderation issues, currently we have no worries of that. But it’ll come to that.
> > > 
> > > 
> > > for now it’s okay for Scratch, if we want to continue this forward we’ll probably have to speak with an ST member
> > 
> > 
> > Yep, or we have to think of a domain idea.
> 
> Wdym “domain idea”?

We’re using .github.io as our extension... I think I’d rather talk to an ST member about this.

**Comment by Mapletron** [comment]
Yeah, I don’t know if we thought this through...

**Comment by B294** [comment]
> Yeah, I don’t know if we thought this through...

You can talk to an ST member about it. If you know any, go ahead and do it now. I don’t know any.

**Comment by Mapletron** [comment]
I’ll figure something out.

**Comment by Spaceflyer234** [comment]
Well, while you guys figure this out I'm gonna work on a block-based programming language engine.

**Comment by Mapletron** [comment]
> Well, while you guys figure this out I'm gonna work on a block-based programming language engine.

“block-based programming language engine?”

**Comment by Spaceflyer234** [comment]
> > Well, while you guys figure this out I'm gonna work on a block-based programming language engine.
> 
> “block-based programming language engine?”

Like blockly.

**Comment by Mapletron** [comment]
so deleting signup or not..?

**Comment by B294** [comment]
> so deleting signup or not..?

Keeping it.

**Comment by JimmyRooster** [comment]
> so deleting signup or not..?

We can have sign up without email can't we?
Then you can still have a system with unshared projects and we don't need to track emails.

**Comment by Spaceflyer234** [comment]
> > so deleting signup or not..?
> 
> We can have sign up without email can't we?
> Then you can still have a system with unshared projects and we don't need to track emails.

Yes, Can you start on the database?

**Comment by JimmyRooster** [comment]
> > > so deleting signup or not..?
> > 
> > 
> > We can have sign up without email can't we?
> > Then you can still have a system with unshared projects and we don't need to track emails.
> 
> Yes, Can you start on the database?

So what database where we using?

**Comment by Spaceflyer234** [comment]
> > > > so deleting signup or not..?
> > > 
> > > 
> > > We can have sign up without email can't we?
> > > Then you can still have a system with unshared projects and we don't need to track emails.
> > 
> > 
> > Yes, Can you start on the database?
> 
> So what database where we using?

Whatever you think.

**Comment by B294** [comment]
> > > > so deleting signup or not..?
> > > 
> > > 
> > > We can have sign up without email can't we?
> > > Then you can still have a system with unshared projects and we don't need to track emails.
> > 
> > 
> > Yes, Can you start on the database?
> 
> So what database where we using?

@JimmyRooster  DynamoDB. This one. Can you get started whenever you're reading this?

**Comment by B294** [comment]
> > > so deleting signup or not..?
> > 
> > 
> > We can have sign up without email can't we?
> > Then you can still have a system with unshared projects and we don't need to track emails.
> 
> Yes, Can you start on the database?

What about bots?
