### ISSUE TITLE
Using scratch editor

### ISSUE THREAD

**Issue by jemunm378** [GrooveProgramming/editor#13]
Now, what I was thinking of doing is forking the scratch editor and we can add blocks using that. What do you guys think of this idea?

**Comment by Mapletron** [comment]
I don’t know if we should do this, there are both beneficial and negative effects. We’ve come pretty far since the beginning, should we throw that all away now? That being said we would have a lot more done since the Scratch editor is quite further ahead of us in terms of our progress.

**Comment by B294** [comment]
I disagree. Mission complete. Lol

**Comment by Mapletron** [comment]
> I disagree. Mission complete. Lol

Wdym “mission complete”?

**Comment by B294** [comment]
> > I disagree. Mission complete. Lol
> 
> Wdym “mission complete”?

I was referring to a joke in a different issue. Short answer - Not worth it. My actual opinion - Nope. Why would we spend all this time and then fork the Scratch editor? Also, we can make our own blocks called Groove blocks when we are done as Scratch did when they used blockly.

**Comment by jemunm378** [comment]
Okay, case closed

**Comment by jemunm378** [comment]
> > > I disagree. Mission complete. Lol
> > 
> > 
> > Wdym “mission complete”?
> 
> I was referring to a joke in a different issue. Short answer - Not worth it. My actual opinion - Nope. Why would we spend all this time and then fork the Scratch editor? Also, we can make our own blocks called Groove blocks when we are done as Scratch did when they used blockly.

We should work on the blocks though...
