### ISSUE TITLE
This is a block editor, not a VM... VM stuff will go somewhere else not in the original Blockly code.

### ISSUE THREAD

**Issue by AmazingMech2418** [GrooveProgramming/editor#15]
https://github.com/GrooveProgramming/editor/blob/696c7cf1ce360b52ea3ae71862f7449e9dbc4f23/blocks/colour.js#L124

**Comment by jemunm378** [comment]
Oh okay

**Comment by AmazingMech2418** [comment]
@jemunm378 If you could revert https://github.com/GrooveProgramming/editor/commit/696c7cf1ce360b52ea3ae71862f7449e9dbc4f23 , that would be great. (I don't have access to this repo since I wasn't even invited to the org.
