### ISSUE TITLE
Issue Loading Projects

### ISSUE THREAD

**Issue by Spaceflyer234** [GrooveProgramming/editor#8]
**Describe the bug**

Loading a project twice will double-up the code.

**To Reproduce**

1. Go to the editor and make a simple project 
2. Click on save code
3. Click load code and paste you save code
4. You will see the code is doubled up.

**Expected behavior**

The code should be replaced before loading.

**Comment by B294** [comment]
I think you should delete/replace the code. But give an alert for it first

**Comment by B294** [comment]
https://jemunm378.github.io/ScratchHelp.github.io/Chat.html meet me here

**Comment by Spaceflyer234** [comment]
Also, loading seems to be broke for big projects.

**Comment by B294** [comment]
> Also, loading seems to be broke for big projects.

Oh...
